name: Manual Build

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type'
        required: true
        default: 'debug'
        type: choice
        options:
        - debug
        - release
      skip_tests:
        description: 'Skip tests'
        required: false
        default: false
        type: boolean

jobs:
  build:
    name: Manual Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install dependencies
      run: npm ci --legacy-peer-deps

    - name: Run tests
      if: ${{ !inputs.skip_tests }}
      run: npm test

    - name: Make gradlew executable
      run: chmod +x android/gradlew

    - name: Create release keystore from secrets
      if: ${{ inputs.build_type == 'release' }}
      run: |
        echo "${{ secrets.RELEASE_KEYSTORE }}" | base64 -d > android/app/release-key.keystore
        echo "MYAPP_RELEASE_STORE_FILE=release-key.keystore" >> android/gradle.properties
        echo "MYAPP_RELEASE_KEY_ALIAS=${{ secrets.RELEASE_KEY_ALIAS }}" >> android/gradle.properties
        echo "MYAPP_RELEASE_STORE_PASSWORD=${{ secrets.RELEASE_STORE_PASSWORD }}" >> android/gradle.properties
        echo "MYAPP_RELEASE_KEY_PASSWORD=${{ secrets.RELEASE_KEY_PASSWORD }}" >> android/gradle.properties

    - name: Build Debug APK
      if: ${{ inputs.build_type == 'debug' }}
      run: |
        cd android
        ./gradlew assembleDebug --no-daemon

    - name: Build Release APK
      if: ${{ inputs.build_type == 'release' }}
      run: |
        cd android
        ./gradlew assembleRelease --no-daemon

    - name: Upload Debug APK
      if: ${{ inputs.build_type == 'debug' }}
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk-${{ github.run_number }}
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 7

    - name: Upload Release APK
      if: ${{ inputs.build_type == 'release' }}
      uses: actions/upload-artifact@v4
      with:
        name: release-apk-${{ github.run_number }}
        path: android/app/build/outputs/apk/release/app-release.apk
        retention-days: 14
